task: ic50_reg
sub_type: aa

# Data
data_name: bio_reg
label_name: target
peptide_name: peptide
methods: thioether
max_workers: 16
origin_data_dir: ../data/origin_data
graph_data_dir: ../data/graph_data
prediction_dir: ../prediction

# Trainer
in_feats: 40
max_evals: 30
loop: true
device: cuda

# Model
rgcn_hidden_feats: [64, 64, 64, 64]
ffn_hidden_feats: 128
rgcn_drop_out: 0.05
ffn_drop_out: 0.05
lr: 0.001
mode: higher
metric_name: r2
classification: false
batch_size: 2048
patience: 40
