rgcn_hidden_feats: [64, 64, 64, 64]
ffn_hidden_feats: 64
rgcn_drop_out: 0.1
ffn_drop_out: 0.1
lr: 0.01
mode: higher
metric_name: r2
classification: false
batch_size: 512

pretrained_model: affinity_reg_aa_early_stop.pth