rgcn_hidden_feats: [64, 64, 64, 64]
ffn_hidden_feats: 128
rgcn_drop_out: 0.05
ffn_drop_out: 0.15
lr: 0.001
mode: higher
metric_name: r2
classification: false
batch_size: 2048
patience: 40
num_epochs: 500